aliyun.endpoint = ${ALIYUN_ENDPOINT}
aliyun.accesskey_id = ${ALIYUN_ACCESSKEY_ID}
aliyun.ccesskey_secret = ${ALIYUN_ACCESSKEY_SECRET}

aliyun.oss_bucket_name = ${ALIYUN_OSS_BUCKET_NAME}
aliyun.oss_bucket_url = ${ALIYUN_OSS_BUCKET_URL}
aliyun.oss_region = ${ALIYUN_OSS_REGION}
aliyun.oss_folder = ${ALIYUN_OSS_FOLDER}
